const letters = [
	{
		button: 0,
		all: ['`', '~', 'ё', 'Ё'],
		eng: ['`', '~'],
		engName: ['`', '~'],
		rus: ['ё', 'Ё'],
		rusName: ['Ё'],
	},
	{
		button: 1,
		all: ['1', '!'],
		eng: ['1', '!'],
		rus: ['1', '!'],
	},
	{
		button: 2,
		all: ['2', '@', '"'],
		eng: ['2', '@'],
		rus: ['2', '"'],
	},
	{
		button: 3,
		all: ['3', '#', '№'],
		eng: ['3', '#'],
		rus: ['3', '№'],
	},
	{
		button: 4,
		all: ['4', '$', ';'],
		eng: ['4', '$'],
		rus: ['4', ';'],
	},
	{
		button: 5,
		all: ['5', '%'],
		eng: ['5', '%'],
		rus: ['5', '%'],
	},
	{
		button: 6,
		all: ['6', '^', ':'],
		eng: ['6', '^'],
		rus: ['6', ':'],
	},
	{
		button: 7,
		all: ['7', '&', '?'],
		eng: ['7', '&'],
		rus: ['7', '?'],
	},
	{
		button: 8,
		all: ['8', '*'],
		eng: ['8', '*'],
		rus: ['8', '*'],
	},
	{
		button: 9,
		all: ['9', '('],
		eng: ['9', '('],
		rus: ['9', '('],
	},
	{
		button: 10,
		all: ['0', ')'],
		eng: ['0', ')'],
		rus: ['0', ')'],
	},
	{
		button: 11,
		all: ['-', '_'],
		eng: ['-', '_'],
		rus: ['-', '_'],
	},
	{
		button: 12,
		all: ['=', '+'],
		eng: ['=', '+'],
		rus: ['=', '+'],
	},
	{
		button: 13,
		all: ['Backspace'],
		eng: ['Backspace', 'Backspace'],
		rus: ['Backspace', 'Backspace'],
	},
	{
		button: 14,
		all: ['Tab'],
		eng: ['Tab', 'Tab'],
		rus: ['Tab', 'Tab'],
	},
	{
		button: 15,
		all: ['q', 'Q', 'й', 'Й'],
		eng: ['q', 'Q'],
		rus: ['й', 'Й'],
	},
	{
		button: 16,
		all: ['w', 'W', 'ц', 'Ц'],
		eng: ['w', 'W'],
		rus: ['ц', 'Ц'],
	},
	{
		button: 17,
		all: ['e', 'E', 'у', 'У'],
		eng: ['e', 'E'],
		rus: ['у', 'У'],
	},
	{
		button: 18,
		all: ['r', 'R', 'к', 'К'],
		eng: ['r', 'R'],
		rus: ['к', 'К'],
	},
	{
		button: 19,
		all: ['t', 'T', 'е', 'Е'],
		eng: ['t', 'T'],
		rus: ['е', 'Е'],
	},
	{
		button: 20,
		all: ['y', 'Y', 'н', 'Н'],
		eng: ['y', 'Y'],
		rus: ['н', 'Н'],
	},
	{
		button: 21,
		all: ['u', 'U', 'г', 'Г'],
		eng: ['u', 'U'],
		rus: ['г', 'Г'],
	},
	{
		button: 22,
		all: ['i', 'I', 'ш', 'Ш'],
		eng: ['i', 'I'],
		rus: ['ш', 'Ш'],
	},
	{
		button: 23,
		all: ['o', 'O', 'щ', 'Щ'],
		eng: ['o', 'O'],
		rus: ['щ', 'Щ'],
	},
	{
		button: 24,
		all: ['p', 'P', 'з', 'З'],
		eng: ['p', 'P'],
		rus: ['з', 'З'],
	},
	{
		button: 25,
		all: ['[', '{', 'х', 'Х'],
		eng: ['[', '{'],
		rus: ['х', 'Х'],
	},
	{
		button: 26,
		all: [']', '}', 'ъ', 'Ъ'],
		eng: [']', '}'],
		rus: ['ъ', 'Ъ'],
	},
	{
		button: 27,
		all: ['\\', '|', '\\', '/'],
		eng: ['\\', '}'],
		rus: ['\\', '/'],
	},
	{
		button: 28,
		all: ['Delete'],
		eng: ['Delete', 'Delete'],
		rus: ['Delete', 'Delete'],
	},
	{
		button: 29,
		all: ['CapsLock'],
		eng: ['Caps lock', 'Caps lock'],
		rus: ['Caps lock', 'Caps lock'],
	},
	{
		button: 30,
		all: ['a', 'A', 'ф', 'Ф'],
		eng: ['a', 'A'],
		rus: ['ф', 'Ф'],
	},
	{
		button: 31,
		all: ['s', 'S', 'ы', 'Ы'],
		eng: ['s', 'S'],
		rus: ['ы', 'Ы'],
	},
	{
		button: 32,
		all: ['d', 'D', 'в', 'В'],
		eng: ['d', 'D'],
		rus: ['в', 'В'],
	},
	{
		button: 33,
		all: ['f', 'F', 'а', 'А'],
		eng: ['f', 'F'],
		rus: ['а', 'А'],
	},
	{
		button: 34,
		all: ['g', 'G', 'п', 'П'],
		eng: ['g', 'G'],
		rus: ['п', 'П'],
	},
	{
		button: 35,
		all: ['h', 'H', 'р', 'Р'],
		eng: ['h', 'H'],
		rus: ['р', 'Р'],
	},
	{
		button: 36,
		all: ['j', 'J', 'о', 'О'],
		eng: ['j', 'J'],
		rus: ['о', 'О'],
	},
	{
		button: 37,
		all: ['k', 'K', 'л', 'Л'],
		eng: ['k', 'K'],
		rus: ['л', 'Л'],
	},
	{
		button: 38,
		all: ['l', 'L', 'д', 'Д'],
		eng: ['l', 'L'],
		rus: ['д', 'Д'],
	},
	{
		button: 39,
		all: [';', ':', 'ж', 'Ж'],
		eng: [';', ':'],
		rus: ['ж', 'Ж'],
	},
	{
		button: 40,
		all: ["'", '"', 'э', 'Э'],
		eng: ["'", '"'],
		rus: ['э', 'Э'],
	},
	{
		button: 41,
		all: ['Enter'],
		eng: ['Enter', 'Enter'],
		rus: ['Enter', 'Enter'],
	},
	{
		button: 42,
		all: ['Shift'],
		code: ['ShiftLeft'],
		eng: ['Shift', 'Shift'],
		rus: ['Shift', 'Shift'],
	},
	{
		button: 43,
		all: ['z', 'Z', 'я', 'Я'],
		eng: ['z', 'Z'],
		rus: ['я', 'Я'],
	},
	{
		button: 44,
		all: ['x', 'X', 'ч', 'Ч'],
		eng: ['x', 'X'],
		rus: ['ч', 'Ч'],
	},
	{
		button: 45,
		all: ['c', 'C', 'с', 'С'],
		eng: ['c', 'C'],
		rus: ['с', 'С'],
	},
	{
		button: 46,
		all: ['v', 'V', 'м', 'М'],
		eng: ['v', 'V'],
		rus: ['м', 'М'],
	},
	{
		button: 47,
		all: ['b', 'B', 'и', 'И'],
		eng: ['b', 'B'],
		rus: ['и', 'И'],
	},
	{
		button: 48,
		all: ['n', 'N', 'т', 'Т'],
		eng: ['n', 'N'],
		rus: ['т', 'Т'],
	},
	{
		button: 49,
		all: ['m', 'M', 'ь', 'Ь'],
		eng: ['m', 'M'],
		rus: ['ь', 'Ь'],
	},
	{
		button: 50,
		all: [',', '<', 'б', 'Б'],
		eng: [',', '<'],
		rus: ['б', 'Б'],
	},
	{
		button: 51,
		all: ['.', '>', 'ю', 'Ю'],
		eng: ['.', '>'],
		rus: ['ю', 'Ю'],
	},
	{
		button: 52,
		all: ['/', '?', '.', ','],
		eng: ['/', '?'],
		rus: ['.', ','],
	},
	{
		button: 53,
		all: ['ArrowUp'],
		eng: ['', ''],
		rus: ['', ''],
	},
	{
		button: 54,
		all: ['Shift'],
		code: ['ShiftRight'],
		eng: ['Shift', 'Shift'],
		rus: ['Shift', 'Shift'],
	},
	{
		button: 55,
		all: ['Control'],
		code: ['ControlLeft'],
		eng: ['Ctrl', 'Ctrl'],
		rus: ['Ctrl', 'Ctrl'],
	},
	{
		button: 56,
		all: ['Meta'],
		eng: ['Win', 'Win'],
		rus: ['Win', 'Win'],
	},
	{
		button: 57,
		all: ['Alt'],
		code: ['AltLeft'],
		eng: ['Alt', 'Alt'],
		rus: ['Alt', 'Alt'],
	},
	{
		button: 58,
		all: [' '],
		code: ['Space'],
		eng: ['-----', '-----'],
		rus: ['-----', '-----'],
	},
	{
		button: 59,
		all: ['AltRight'],
		code: ['AltRight'],
		eng: ['Alt', 'Alt'],
		rus: ['Alt', 'Alt'],
	},
	{
		button: 60,
		all: ['ArrowLeft'],
		eng: ['', ''],
		rus: ['', ''],
	},
	{
		button: 61,
		all: ['ArrowDown'],
		eng: ['', ''],
		rus: ['', ''],
	},
	{
		button: 62,
		all: ['ArrowRight'],
		eng: ['', ''],
		rus: ['', ''],
	},
	{
		button: 63,
		all: ['Control'],
		code: ['ControlRight'],
		eng: ['Ctrl', 'Ctrl'],
		rus: ['Ctrl', 'Ctrl'],
	},
];

export default letters;
